import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/header";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-r from-gray-900 via-gray-800 to-gray-700 antialiased`}
      >
        <div className="px-4 md:px-5 mx-auto max-w-[1440px]">
        <Navbar/>
        {children}
        </div>
      </body>
    </html>
  );
}
